services:
  luchparsing:
    build: .
    container_name: luchparsing
    env_file:
      - .env
    environment:
      - CHROMEDRIVER=/usr/bin/chromedriver
      - CHROME_BIN=/usr/bin/chromium
      - DISPLAY=:99
      - LOG_MANUAL_ONLY=0
      - LOG_LEVEL=INFO
    shm_size: "4gb"
    ports:
      - "8000:8000"
    volumes:
      - dbdata:/app/database
      - exportsdata:/app/exports
    restart: unless-stopped

volumes:
  dbdata:
  exportsdata: